### ISSUE TITLE
Argument: endpoint

### ISSUE THREAD

**Issue by sudojunior** [sudojunior/access-groups#21]
**_Future_**

Links back to sudojunior/test-action#6 with enterprise site admin.

```yml
# predefined jobs / steps
- uses: sudojunior/access-check@main
  with:
    endpoint: https://git.example.com/api # defaulting to https://api.github.com
```
